### ISSUE TITLE
Settings menu shifts portions of main screen out of view

### ISSUE THREAD

**Issue by kchiou** [ethoinformatics/ethoinfo-project-app#5]
Posted for Tony:

This is a minor thing, and more a peeve of mine, but currently when one opens the hamburger, the right side of the screen shifts and the + button is off screen to right, so you cannot "add" anything if the hamburger window is open... but it makes sense to me to still have the + there and be able to interact even with the hamburger menu open.

**Comment by kchiou** [comment]
(Kenny now) I agree and reproduced this. It makes more sense to me for the Settings hamburger menu to slide to the right over the main screen rather than shifting the main screen itself. But with a narrow mobile screen, I wonder whether the user should even be working in the main screen with the Settings menu active. I think @difiore is just conveying his frustration at being able to NEARLY see the "plus" button but not being able to reach it. If the main screen was entirely eclipsed by the settings menu, we would probably feel less anxiety.

**Comment by tigoe** [comment]
I disagree with Tony here. I think when the hamburger is open, the main screen should slide away and you should just interact with settings until you're done. When you're messing with settings, it's always better to finish with the settings before you return to active screens that depend on those settings.

And to Kenny's point, it's a very good idea to work with the app in device mode. Narrow your window to make it more portrait mode, to get a better sense of reality.

**Comment by difiore** [comment]
point taken, but my point is that (to me) it's confusing visually to 
have the main screen "slide away" -- kenny's solution is fine (to always 
have the hamburger menu cover the whole screen), but if not in device 
mode, then it seems like setting should instead slide over top of the 
main screen (rather than replace the whole main screen). also, are the 
no cases where the main screen would be updating while you work on the 
setting screens? e.g., if you're there on settings for a while, would a 
map on the main screen not update?

**Comment by tigoe** [comment]
> On Apr 10, 2016, at 1:09 PM, Anthony Di Fiore notifications@github.com wrote:
> 
> point taken, but my point is that (to me) it's confusing visually to 
> have the main screen "slide away" -- kenny's solution is fine (to always 
> have the hamburger menu cover the whole screen), but if not in device 
> mode, then it seems like setting should instead slide over top of the 
> main screen (rather than replace the whole main screen).

Since we’re trying to build only for devices, I don’t think we should try to try to solve a desktop problem at the moment, let’s concentrate on what’s needed for device mode, in the interest of time.

>  also, are the 
> no cases where the main screen would be updating while you work on the 
> setting screens? e.g., if you're there on settings for a while, would a 
> map on the main screen not update?

That’s a situation we was to avoid, You generally don’t want the user hanging out in settings for a long time, because if they change a setting, then hang there for a long time, and assume their setting was saved but it wasn’t, you get a problem. Generally settings are saved when you explicitly hit save, or when you close the settings panel. So, for example, if you applied a change to geolocation update but didn’t apply it, then no, the map panel shouldn’t update with your change until you get out of settings.

t.

**Comment by relevante** [comment]
Are we happy with the current situation here? Can this be closed?

**Comment by tigoe** [comment]
Looks like now settings fills the whole screen, so you can't see the home screen at all until you close it. I prefer that, but let's make sure @difiore is okay with it. Tony?

**Comment by difiore** [comment]
Hi - selections (e.g., settings) from the hamburger always filled the screen. The issue was that hitting hit hamburger to get to settings shifted the screen to the right and made the interacting with the main screen difficult). Tom's point that hanging out and interacting with the main screen with the hamburger open is something that we should discourage... fair enough!

**Comment by tigoe** [comment]
It no longer does that. Tony, update your repo copy and give it a try again and let us know what you think. I updated the readme with directions on how to update your local copy of the repo at the end.

**Comment by difiore** [comment]
Hi  -
I updated my local repo and rebuilt this morning... I'll try that again.

T

**Comment by tigoe** [comment]
And you didn't see a different behavior? Weird. For me, what happens now is that clicking the hamburger moves it to the right, but clicking any settings option brings that setting up full screen from the bottom.

Wait, I see what you mean: if you click the hamburger but DON'T click a setting, but click on something from the main screen off to the right instead, the old error still persists. Nick, check out http://tigoe.net/movies/etho-video.mov, about the 00:26 mark. You'll see what we want to fix, you can still click on some of the main screen, but not all, and the home button is disabled. Better would be to grey out the whole homescreen panel, I think, or find some other way of disabling it and visually indicating that it's not active.

**Comment by relevante** [comment]
The home button is working for me with settings open - I wonder if the target is just a little small and in the video the taps just missed it by a little bit? Either way, I'm not sure that changes the decision. Do we just want to put a semi-transparent layer over the UI to gray it out and block interaction when we're in settings?

**Comment by difiore** [comment]
that sounds like a good idea :)

**Comment by tigoe** [comment]
Agreed, that seems like a good fix. Thanks Nick.

**Comment by relevante** [comment]
This is built in ethoinfo-framework cc3ed70
